/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./src/components/breadcrumbs.vue')['default']
    DialogInfo: typeof import('./src/components/DialogInfo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageNotFound: typeof import('./src/components/PageNotFound.vue')['default']
    RocketCard: typeof import('./src/components/RocketCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
